---
abstract: 'Download a customized version of Twitter Bootstrap'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  File::HomeDir::Test: 0
  FindBin: 0
  Mojo::Message::Response: 0
  Test::Differences: 0
  Test::More: 0
  YAML: 0
  base: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-TwitterBootstrap-Download-Custom
requires:
  Archive::Zip: 0
  DBD::SQLite: 0
  DBI: 0
  File::HomeDir: 0
  File::Temp: 0
  Mojo::DOM: 0
  Mojo::JSON: 0
  Mojo::UserAgent: 0
  Mojolicious: 4.29
  Moose: 0
  Path::Class: 0.26
  Scalar::Util: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/plicease/webservice-twitterbootstrap-download-custom/issues
  homepage: http://perl.wdlabs.com/WebService-TwitterBootstrap-Download-Custom/
  repository: git://github.com/plicease/webservice-twitterbootstrap-download-custom.git
version: 0.03
